#!/bin/bash

export CLUSTER_MANAGER_NAMES=('nightswatch-dev' 'lannisters-dev' 'starks-dev' 'dothrakis-dev' 'ironborns-dev' 'wildlings-dev' 'whitewalkers-dev' 'westeros-dev')
export CLUSTER_WORKER_NAMES=('johnsnow-dev' 'tyrion-dev' 'daenerys-dev' 'cersie-dev' 'melisandre-dev' 'ygritte-dev' 'hodor-dev' 'arya-dev' 'sansa-dev' 'nedstark-dev' 'lordbaelish-dev' 'lordvarys-dev' 'jamie-dev' 'catelyn-dev' 'missandei-dev' 'highsparrow-dev' 'bran-dev')
